### PR TITLE
initial commit prepare mask script

### PR DESCRIPTION
**Pull request by marcgri**

### CODE REVIEW

**Comment by chuckie82** [comment]
Is this Haoyuan's mask generation script? I don't think this script is compatible with Dragonfly.

**Comment by marcgri** [comment]
Yes, it is. I tested it, but had not used it for Dragonfly. It is fine if we don’t use. That means the Trello item should be done now.

**Comment by chuckie82** [comment]
Could you add a comment at the top of this script saying this script does not work.
Also, mention the mask convention used by Dragonfly where 0 means X, 1 means Y, and 2 means Z.

**Comment by marcgri** [comment]
Sure, no problem.

**Comment by marcgri** [comment]
I updated the file and pushed. Do I need a new pull request?

**Comment by chuckie82** [comment]
OK to merge.

**Pull request merged**
